#define E101 "101 Switching Protocols"
#define E102 "102 Processing"
#define E103 "103 Early Hints Experimental"
#define E200 "200 OK"
#define E201 "201 Created"
#define E202 "202 Accepted"
#define E203 "203 Non-Authoritative Information"
#define E204 "204 No Content"
#define E205 "205 Reset Content"
#define E206 "206 Partial Content"
#define E207 "207 Multi-Status"
#define E208 "208 Already Reported"
#define E226 "226 IM Used"
#define E300 "300 Multiple Choices"
#define E301 "301 Moved Permanently"
#define E302 "302 Found"
#define E303 "303 See Other"
#define E304 "304 Not Modified"
#define E307 "307 Temporary Redirect"
#define E308 "308 Permanent Redirect"
#define E400 "400 Bad Request"
#define E401 "401 Unauthorized"
#define E402 "402 Payment Required"
#define E403 "403 Forbidden"
#define E404 "404 Not Found"
#define E405 "405 Method Not Allowed"
#define E406 "406 Not Acceptable"
#define E407 "407 Proxy Authentication Required"
#define E408 "408 Request Timeout"
#define E409 "409 Conflict"
#define E410 "410 Gone"
#define E411 "411 Length Required"
#define E412 "412 recondition Failed"
#define E413 "413 Content Too Large"
#define E414 "414 URI Too Long"
#define E415 "415 Unsupported Media Type"
#define E416 "416 Range Not Satisfiable"
#define E417 "417 Expectation Failed"
#define E418 "418 I'm a teapot"
#define E421 "421 Misdirected Request"
#define E422 "422 Unprocessable Content"
#define E423 "423 Locked"
#define E424 "424 Failed Dependency"
#define E425 "425 Too Early"
#define E426 "426 Upgrade Required"
#define E428 "428 Precondition Required"
#define E429 "429 Too Many Requests"
#define E431 "431 Request Header Fields Too Large"
#define E451 "451 Unavailable For Legal Reasons"
#define E500 "500 Internal Server Error"
#define E501 "501 Not Implemented"
#define E502 "502 Bad Gateway"
#define E503 "503 Service Unavailable"
#define E504 "504 Gateway Timeout"
#define E505 "505 HTTP Version Not Supported"
#define E506 "506 Variant Also Negotiates"
#define E507 "507 Insufficient Storage"
#define E508 "508 Loop Detected"
#define E510 "510 Not Extended"
#define E511 "511 Network Authentication Required"

#include <iostream>
#include <fstream>

#define html "text/html"
#define htm "text/html"
#define shtml "shtml"
#define css "text/css"
#define xml "text/xml"
#define rss "text/xml"
#define gif "image/gif"
#define jpeg "image/jpeg"
#define jpg "image/jpeg"
#define js "application/x-javascript"
#define txt "text/plain"
#define htc "text/x-component"
#define mml "text/mathml"
#define png "image/png"
#define ico "image/x-icon"
#define jng "image/x-jng"
#define wbmp "image/vnd.wap.wbmp"
#define jar "application/java-archive"
#define war "application/java-archive"
#define ear "application/java-archive"
#define hqx "application/mac-binhex40"
#define pdf "application/pdf"
#define cco "application/x-cocoa"
#define jardiff "application/x-java-archive-diff"
#define jnlp "application/x-java-jnlp-file"
#define run "application/x-makeself"
#define pl "application/x-perl"
#define pm "application/x-perl"
#define prc "application/x-pilot"
#define pdb "application/x-pilot"
#define rar "application/x-rar-compressed"
#define rpm "application/x-redhat-package-manager"
#define sea "application/x-sea"
#define swf "application/x-shockwave-flash"
#define sit "application/x-stuffit"
#define tcl "application/x-tcl"
#define tk "application/x-tcl"
#define der "application/x-x509-ca-cert"
#define pem "application/x-x509-ca-cert"
#define crt "application/x-x509-ca-cert"
#define xpi "application/x-xpinstall"
#define zip "application/zip"
#define deb "application/octet-stream"
#define bin "application/octet-stream"
#define exe "application/octet-stream"
#define dll "application/octet-stream"
#define dmg "application/octet-stream"
#define eot "application/octet-stream"
#define iso "application/octet-stream"
#define img "application/octet-stream"
#define msi "application/octet-stream"
#define msp "application/octet-stream"
#define msm "application/octet-stream"
#define mp3 "audio/mpeg"
#define ra "audio/x-realaudio"
#define mpeg "video/mpeg"
#define mpg "video/mpeg"
#define mov "video/quicktime"
#define flv "video/x-flv"
#define avi "video/x-msvideo"
#define wmv "video/x-ms-wmv"
#define asx "video/x-ms-asf"
#define asf "video/x-ms-asf"
#define mng "video/x-mng"
